version: "3.8"
services:
  merchandise-service:
    build: .
    hostname: merchandise-service
    ports:
      - "8080:80"
    image: merchandise_service:main
    container_name: merchandise_service
    depends_on:
      - stock-api
      - emailing-service
      - employees-service
      - supply-service

  stock-api:
    image: ghcr.io/ozon-edu-csharp-2021/stock-api:main
    hostname: stock-api
    ports:
      - "8081:80"
    container_name: stock-api
    
  emailing-service:
    image: ghcr.io/ozon-edu-csharp-2021/emailing-service:main
    hostname: emailing-service
    ports:
      - "8082:80"
    container_name: emailing-service

  employees-service:
    image: ghcr.io/ozon-edu-csharp-2021/employees-service:main
    hostname: employees-service
    ports:
      - "8083:80"
    container_name: employees-service
    
  supply-service:
    image: ghcr.io/ozon-edu-csharp-2021/supply-service:main
    hostname: supply-service
    ports:
      - "8084:80"
    container_name: supply-service
    